import {useState, useEffect} from 'react'

function App() {
  const [numbers, setNumbers] = useState([])
  const [largest, setLargest] = useState(53439)
  const [smallest, setSmallest] = useState(4)

  const sendRequests = () => {

    console.log("Clicked the generate button!");
    // fetch request to 10 instances concurrently for numbers (1k each)
    fetch("http://...")
    .then( res => {
      return res.json()
    })
    .then((data) => {
      setNumbers(data)
    })
    .catch(error => {
      console.warn(error)
    })
  }

  return (
    <div className="App">
      <span className="author">Matteo Rapa | <a href="https://github.com/matteorapa/gcloud-task">CIS3111 Cloud Computing Assignment</a></span>

      <div className="spacing">
        <h1>Generate <strong className="number">10,000</strong> random numbers.</h1>
        <button className="generate-btn" onClick={()=> sendRequests() }>GENERATE</button>
      </div>

      <div className="spacing">
        <h2>The largest generated number is <u>{largest}</u>.</h2>
        <h2>The smallest generated number is <u>{smallest}</u>.</h2>
      </div>

      <div className="spacing">
        <h3 className="number-list-heading">Numbers generated by instances</h3>
        <div className="number-list">
            <div className="number-list-item legend">
              <span>Instance ID</span>
              <span>Generated Number</span>
            </div>
            <div className="number-list-item">
              <span>00c61b117c1eae3d31972c634e55153699d3e801f6b5ff369fa8db865cc2593f2849c482d7dadc7b4db2da56b9c713dc1c119f2331ddf4f46b6885b8f5d7fb82f6ec341a6588d336</span>
              <span>235325</span>
            </div>
           
           
        </div>
      </div>
  
    </div>
  );
}

export default App;
